<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-GrainTrade.Silo-90923bd1-3b47-47d1-b90a-1743fc7150d2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.4" />
    <PackageReference Include="Microsoft.Orleans.Clustering.AdoNet" Version="10.2.2" />
    <PackageReference Include="Microsoft.Orleans.Persistence.AdoNet" Version="10.2.2" />
    <PackageReference Include="Microsoft.Orleans.Reminders.AdoNet" Version="10.2.2" />
    <PackageReference Include="Microsoft.Orleans.Server" Version="10.2.2" />
    <PackageReference Include="Npgsql" Version="9.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GrainTrade.Grains\GrainTrade.Grains.csproj" />
  </ItemGroup>
</Project>
